S3_API_KEY_ID: AKIAJNB332Z2XL63I2JA
S3_API_SECRET_KEY: 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
S3_API_REGION: us-west-2
S3_API_BUCKET: timechat

MANDRILL_USERNAME: app32811511@heroku.com
MANDRILL_APIKEY: irr5czhodNjqHc8ul_6iLg