# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259bf451c47388053076e34598e219d00a6dafb83b1701a9586aa7fa8a47eabfd239332f6a19e46a7da3d2ef89654e2b4b4a39a5187fcb030835056199ca4f7f

test:
  secret_key_base: d61e13a274687cea195e56abaa01d4a9cd1ea41563875b5ca7d2035bdf482c98db3945a07d793f3b816f4f708b2a547412b202d33afb7d1d180de34eb285f098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
